cmake_minimum_required(VERSION 3.17)
project(LeetCode_Hashtable)

set(CMAKE_CXX_STANDARD 14)
include_directories(util)
add_executable(LeetCode_Hashtable main.cpp L1_twoSum/twoSum.cpp L1_twoSum/twoSum.h util/util.h test_factory.h L3_lengthOfLongestSubstring/lengthOfLongestSubstring.cpp L3_lengthOfLongestSubstring/lengthOfLongestSubstring.h L12_intToRoman/L12_intToRoman.cpp L12_intToRoman/L12_intToRoman.h L13_romanToInt/L13_romanToInt.cpp L13_romanToInt/L13_romanToInt.h L17_letterCombinations/L17_letterCombinations.cpp L17_letterCombinations/L17_letterCombinations.h L30_findSubstring/L30_findSubstring.cpp L30_findSubstring/L30_findSubstring.h L36_isValidSudoku/L36_isValidSudoku.cpp L36_isValidSudoku/L36_isValidSudoku.h L37_solveSudoku/L37_solveSudoku.cpp L37_solveSudoku/L37_solveSudoku.h L41_firstMissingPositive/L41_firstMissingPositive.cpp L41_firstMissingPositive/L41_firstMissingPositive.h L49_groupAnagrams/L49_groupAnagrams.cpp L49_groupAnagrams/L49_groupAnagrams.h)